name:         Parse-NetApp-ASUP
version:      VERSIONTAG
version_from: lib/Parse/NetApp/ASUP.pm
installdirs:  site
requires:
	File::Slurp:	9999.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21